- README.md
- irods/query.py
This patch adds aggregation feature to query search.
min, max, sum, avg, count aggregations are available.
> Add aggregation feature for query

- irods/message/__init__.py
I experienced some errors raised while receiving irods messages. The errors occurred because socket.recv call with MSG_WAITALL can still return less data than requested in various situations (i.e. interrupt is raised). This fix introduces a new wrapper function that does an additional check for the length of received data.
> Do not rely on socket.MSG_WAITALL flag

- irods/pool.py
- irods/session.py
- irods/test/pool_test.py
This PR addresses #35 and #36.
> Fix cleanup pooled connections

- irods/data_object.py
- irods/manager/data_object_manager.py
- irods/message/__init__.py
- irods/test/data_obj_test.py
This adds a truncate operation to data object class.
A test case is also included.
> Add a truncate operation to data object

- README.md
Took me some time to get my head around both these new features, so I thought I'd document for everyone and give back, even if only slightly...
> Document use of SpecificQuery class and irods_environment.json functionality

- README.md
- setup.py
I thought I'd document the work on #81 since it helped me.
Also I thought I'd bump the version number since master is really 0.6.0 ++ If we could bump the minor version every time a small change is made, this will help people who try and install via the git pull method, but already have a prior released version installed. Hope thats OK, and just a thought - happy to explore other ways of doing that.
> Added documentation for using try..catch for Specific Query and cheekily bumping version

- irods/results.py
Hello All, 
I add a new function in results.py to print in HTML the result of some request.
> Add function get_html_string in results.py

- irods/message/__init__.py
silently skip Winerror 10045 and reraise other OSErrors
> [#103] handle Winerror 10045

- irods/manager/collection_manager.py
- irods/test/collection_test.py
Adding support for recursive collection creation. I haven't tested this yet! I quickly wanted to get the PR in before I leave for a conference :)
> Add recursive collection creation support, plus test

- irods/manager/user_manager.py
- irods/message/property.py
- irods/rule.py
- irods/test/admin_test.py
- irods/test/data_obj_test.py
- irods/test/query_test.py
Fixed HTML escaping for filenames
Fixed tests for MySQL
Fixed password test
---
[CI tests passed](http://172.25.14.63:8080/job/python-irodsclient-test-workflow/316/)
> A few fixes

- irods/__init__.py
- irods/connection.py
- irods/exception.py
- irods/message/__init__.py
Implementation of PAM auth as discussed in issue https://github.com/irods/python-irodsclient/issues/8
> [#8] PAM Authentication

- irods/manager/data_object_manager.py
- irods/test/data_obj_test.py
[irods#148] DataObjectManager.put() should return reference to new object
> [#148] DataObjectManager.put() should return reference to new object

- irods/column.py
- irods/test/data_obj_test.py
- irods/test/query_test.py
[CI tests passed](http://172.25.14.63:8080/job/python-irodsclient-test-workflow/335/)
Running automated ingest tests now.
Fix courtesy of @lwesterhof
> [#124] Convert strings going to irods to Unicode

- irods/test/query_test.py
Passed in CI, test [362](
http://172.25.14.63:8080/job/python-irodsclient-test-workflow/362/)
> Test auto close queries

- irods/message/__init__.py
- irods/query.py
- irods/test/query_test.py
Passes full suite of tests at the bench using both Python2 and Python3
> [#135] Allow multiple criteria based on column name

- irods/manager/access_manager.py
- irods/test/access_test.py
bench tested on Ubuntu 16.04 / iRODS 4.2.8 under both python2 & python3
> [#207] add raw-acl permissions getter

- irods/connection.py
- irods/session.py
tested on top of #191  using this [test harness](https://github.com/d-w-moore/misc/blob/prc_pam_test/harness/pam_test.sh)
> Disallow PAM auth cleartext passwords

- irods/test/login_auth_test.py
- irods/test/setupssl.py
All testing done previously by this test harness is now imported to run as part of the suite.  It still remains for things to be wired in properly for CI.
> [209] pam/ssl/env auth tests imported from test harness

- irods/rule.py
- irods/test/data_obj_test.py
- irods/test/rule_test.py
PRC test suite now passes under Python2 and Python3
> [#214] [#3] Fix Python3 tests

- irods/exception.py
- irods/test/data_obj_test.py
Will test along with other PR's when python client dot is ready, which will be soon.
> [#250] add exception for SYS_INVALID_INPUT_PARAM

- irods/test/query_test.py
Two tests querying for unicode object names got minor changes / refactor.
The tests were failing at bench, but passing in CI. With this commit, they are green in both places.
> calculate common vault dir for unicode query tests

- irods/message/__init__.py
- irods/test/ticket_test.py
- irods/ticket.py
4.2.11 was failing on the ticket tests which had passed for 4.2.10 prior to the addition of admin -M into server ticket routines.
Thus, this introduces  adaptive class definition for the TicketAdminRequeset so that Tickets work for both 4.2.11 and pre-4.2.11 servers.
> server admin option (for 4.2.11) required corresponding PRC change

- docker-compose.yml
- docker_build/Dockerfile.provider
- docker_build/install_python_rule_engine
- irods/data_object.py
- irods/exception.py
- irods/manager/data_object_manager.py
- irods/manager/metadata_manager.py
- irods/message/__init__.py
- irods/session.py
- irods/test/access_test.py
- irods/test/data_obj_test.py
- irods_consortium_continuous_integration_test_module.py
Allow tests to pass for the Python iRODS Client on main branch (iRODS 4.3.0) as well as on 4-2-stable (for future releases >=4.2.12)
> [#3] Main 4.3.0 tests

- irods/connection.py
- irods/exception.py
- irods/test/PRC_issue_362.bats
- irods/test/login_auth_test.py
Adaptation of solution per @lwesterhof  for #362
> [_362] escape special characters in PAM passwords

- README.rst
- irods/manager/metadata_manager.py
- irods/meta.py
- irods/test/meta_test.py
Example use:
```
metas = data_obj.metadata( timestamps = True ).get_all('someKey')
```
> Metadata timestamps optional

- irods/exception.py
- irods/test/exception_test.py
- irods/test/helpers.py
* includes the OS/Errno information = (abs(server_error_int_result) % 1000)
> [_400] more advanced iRODSException representation

- irods/data_object.py
Expose the property "comments" as checksum or size for object replica
> Get property comments from replica object

- irods/test/data_obj_test.py
The commit within this PR contains a test for the functionality provided in https://github.com/irods/python-irodsclient/pull/449
> Replica comments test

- README.rst
- irods/column.py
- irods/query.py
- irods/session.py
- irods/test/query_test.py
This implements case-insensitive GenQueries ( issue #234 )
> Implement case-insensitive queries (#234)

- README.rst
- irods/__init__.py
- irods/client_configuration/__init__.py
- irods/connection.py
- irods/manager/data_object_manager.py
- irods/session.py
- irods/test/data_obj_test.py
- irods/test/helpers.py
- irods/test/modules/test_auto_close_of_data_objects__issue_456.py
- irods/test/modules/test_saving_and_loading_of_settings__issue_471.py
> Close out-of-scope open data object handles

- irods/client_configuration/__init__.py
- irods/manager/data_object_manager.py
- irods/resource.py
- irods/test/helpers.py
- irods/test/resource_test.py
This is because -1 can wrap to (1L<<64)-1 in the server.
> [_462][_399] Default the dataSize to 0; prefer DATA_SIZE_KW to stat

- irods/data_object.py
- irods/manager/data_object_manager.py
- irods/test/data_obj_test.py
replication now obeys irods_default_resource setting in environment.
> [_459] respect the default_resource setting for replication

- README.md
The example was using `unlink` rather than `trim`.  Here, we correct that -- as unlink would potentially remove all replicas!  The addition of `trim` occurred in v1.1.7 but this commit updates the README accordingly, also correcting a couple of other flaws.
> [504] fix repl_and_trim example

- README.md
just the README portion, no code changes
> [510] update README to reflect removal of session.permissions

- irods/test/data_obj_test.py
Tests for issue #452 needed this.
> [#3] make sure tempfile.mktemp imported where needed for tests

- irods/manager/metadata_manager.py
> [#576] Add missing admin_mode for metadata.apply_atomic_operations

- irods/test/meta_test.py
Test for atomically setting metadata using the admin flag.
> [#576] test new admin mode in atomic metadata API endpoint

- irods/test/pool_test.py
Fix the flood of XML being printed out from pool_test and any tests run on the same terminal thereafter within the same PRC suite run. Affected command : `cd <REPO>/irods/test ; python runner.py`
> [#567] Curb log output to stderr for (and after) pool_test

- irods/api_number.py
- irods/data_object.py
- irods/exception.py
- irods/manager/data_object_manager.py
- irods/test/data_obj_test.py
> [_534] implement replica truncate

- CHANGELOG.rst
- irods/version.py
confirming this builds as py2/3 universal as expected.
> [3] v2.1.0 and update changelog

- irods/connection.py
There is a race condition in BSD (of which MacOS is a decendent) where socket.shutdown() only succeeds if the socket is still open.
If the socket is closed, the call fails with
OSError: [Errno 57] Socket is not connected
Linux and Windows do not error out if the socket is closed.
> [657] catch Errno 57 on MacOS from socket.shutdown()

- irods/connection.py
This is a minor tweak related to the comment in https://github.com/irods/python-irodsclient/issues/691#issuecomment-2760907483
> [5] Fix missing import in connection.py

- irods/helpers/__init__.py
- irods/test/helpers.py
Moved function definitions for make_session and home_collection to irods.helpers module.
Made irods.test.helpers versions of those functions import and/or derive from those definitions.
> [735,ibridges-324] remove dependency on test folder

- irods/manager/user_manager.py
GeneralAdminRequest in iRODS 5 now forbids creation of a user of type 'rodsgroup'. Therefore, in creating a new rodsgroup, the token 'group' must be employed in place of 'user'.
> [#742] change keyword user=>group for adding a rodsgroup
