irods/python-irodsclient

irods/manager/metadata_manager.py
This adds a set operation for metadata to metadata_manager class. This is useful when client need to create a new metadata or update a value of a metadata if exists.
=> Add set operation for metadata

irods/manager/data_object_manager.py
I just re-used the `move()` method of `DataObjectManager`, changing `api_number['DATA_OBJ_RENAME_AN']` to `api_number['DATA_OBJ_COPY_AN']`. Seems to work:
```
>>> from irods.session import iRODSSession
>>> sess = iRODSSession(host='data.iplantcollaborative.org', port=1247, user='test-cmart', password='hi github!', zone='iplant')
>>> sess.data_objects.copy("/iplant/home/test-cmart/testfile2", "/iplant/home/test-cmart/testfile")
>>> sess.data_objects.copy("/iplant/home/test-cmart/xenial-server-cloudimg-amd64-disk1.img", "/iplant/home/test-cmart/iso-copy")
>>> exit()
```
```
cmart@ipc-cmart:~$ ils -l
/iplant/home/test-cmart:
test-cmart        0 CyVerseRes;dustyRes    313851904 2017-04-04.09:07 & iso-copy
test-cmart        0 CyVerseRes;juniorRes            0 2017-04-04.09:03 & testfile …
```
=> Adding support for data object copy

irods/account.py, irods/connection.py
Use the same naming as iRODS environment variable irods_authentication_scheme
=> Use the same naming as iRODS environment variable

README.rst
replaced: `print x` into `print(x)`
=> Python 2 and 3 support for README.rst

irods/manager/data_object_manager.py, irods/session.py
This may not be the best solution because it will be incorrect if the server has different `os.O_*` flags than those defined on Linux.
@adetorcy feel free to criticize
=> [#104] force open flags to client os independent values

irods/models.py
My use of python-irods with my irods wasn't happy until I included this.  I see that it is defined in irods source https://github.com/irods/irods/blob/0a242756ac02f7d52b4bf56408538234ecefc2cb/lib/core/include/rodsGenQuery.h#L185 
seems like it should be here too.
=> add D_RESC_ID

irods/models.py, irods/resource.py, irods/test/admin_test.py
The cause of #111 is that in irods 4.2 resources no longer list their children in the iCAT as per irods/irods#3039. A query on `Resource.children` will return `None`.
This fix addresses this by finding resources whose parent is the current resource. In addition the return value of `resource.children` has been modified for greater usability. Instead of getting a string of resource names, e.g `'ufs1{cache};ufs2{archive}'` we now get a list of actual resource objects with all their attributes, e.g:
```python
for child in resource.children:
print(child.name)
print(child.id)
print(child.type)
print(child.location)
print(child.parent_context)
```
=> Lazy load resource children

irods/connection.py, irods/data_object.py, irods/message/__init__.py
File downloading (in `iRODSDataObjectFileRaw.readinto()`) is changed in order to put received data directly into the intended buffer (exposing `socket.recv_into()` through `Connection` object),  instead of copying from the output of `socket.recv()`.
In my tests, this allows a speedup of some 30% on a 1GB file.
=> [#114] use socket.recv_into() to speed up file download

README.rst
The new section in README.rst, actually called "Recherché queries," shows a couple of new ways to filter LIGQ-like queries in ways not already directly supported in this Python library.
=> add new docs section on rare queries

irods/query.py
Currently the arguments passed to a SpecificQuery instance are keyed starting with "arg0". However, the SpecificQueryRequest accepts arguments starting with "arg1".
This change fixes this by increasing the key values on the SpecificQuery arguments by 1.
=> Fix specific query argument labeling

irods/rule.py
I'm not sure this is the intended behaviour but I have a static rule body without `INPUT` or `OUTPUT` and wish to supply this dynamically. Before this commit, it was either possible to 1) read everything from file or 2) supply everything (having to pass a body in addition to I/O).
=> Allow input, output while reading rule from file

irods/data_object.py, irods/test/data_obj_test.py
Finding out the full resource hierarchy is important for dealing with replicas. In the past, we had a naming scheme that allowed us to work around it, but now that naming scheme doesn't provide what we need. Including resc_hier in the replicas information allows us to do it the right way, and is hopefully useful for others
=> Include resc_hier in replica information

irods/exception.py, irods/query.py
Hello,
We ran into an issue with [a python script](https://github.com/UtrechtUniversity/irods-consistency-check/blob/master/ichk/check.py) that executes many queries:
Query methods `one`, `first` and `get_results` do not close the query, leading to a CAT_STATEMENT_TABLE_FULL error after ~50 `.first()` queries are executed in a single session.
Arguably the programmer may be made responsible for closing queries, however the implementation of e.g. `first` appears to make this impossible (the `continue_index` is inaccessible).
`get_results()` works as long as all results are handled: An early `break`, exiting the generator, leaves the query open.
---
This change automatically closes open queries after early `get_results()` generator exit, and after the first resultset of `one()` and `first()` …
=> Fix CAT_STATEMENT_TABLE_FULL by auto closing queries

irods/test/user_group_test.py, irods/user.py
This pull request resolves #167 by adding a metadata property to user objects and usergroup objects, so metadata can be handled in the same way as with collections and data objects
=> Add metadata property to user and usergroup objects

irods/test/helpers.py, irods/test/user_group_test.py, irods/user.py
Passed in [CI](http://172.25.14.63:8080/job/python-irodsclient-test-workflow/368/)
Incorporates evwieringen [pull request](https://github.com/irods/python-irodsclient/pull/168) with whitespace (and other) corrections, plus enhancements to the tests.
=> [#167] Add metadata for user and usergroup objects

irods/manager/data_object_manager.py, irods/query.py
Query objects now can utilize the builder method "add_keyword" to set keyword options on API requests.
This provides a way to direct a query to a remote (federated) zone using the `ZONE_KW` keyword.
=> [163] add keywords to query objects

irods/message/__init__.py, irods/test/query_test.py
The last fix for issue #135 was lacking in one respect, the ability to query for two AVU's with identical conditions on the AVU-name but, for instance, different conditions on the AVU-value.  This was due to unnecessary checking of duplicate in the series of filters applied to a query.  New tests are in this commit as well, and as before, the entire suite of tests passed for both Python 2 and 3.
=> [#135] fix queries for multiple AVUs of same name

irods/test/data_obj_test.py
These tests will be skipped for iRODS versions 4.2.7 and less due to instability (agent dies, client hangs). Tip of iRODS main repo (4-2-stable and master) will pass the new tests when PR's for #4796 are merged:
- [irods#4793](https://github.com/irods/irods/pull/4793)
- [irods#4794](https://github.com/irods/irods/pull/4794)
=> [irods/irods#4796] add data object copy tests

irods/test/user_group_test.py
test_user_dn was failing, preventing 'rodsuser' from being removed,
causing subsequent tests to fail on creation of the same user
=> [3] remove order sensitivity in test_user_dn

irods/connection.py, irods/message/__init__.py, irods/pool.py, irods/session.py, irods/test/login_auth_test.py
The below example client would report  "myApp" as its **application name** to the iRODS server, and you can see this
via the  `ips` command while the example is running. If the `name` keyword is not supplied for iRODSSession(...), the  contents of the `spOption` environment variable or the default app name of "python-irodsclient" will be assigned, currently with that order of override, though that is subject to change.
```
import time
import os
from irods.session import iRODSSession
if __name__ == '__main__':
try:
env_file = os.environ['IRODS_ENVIRONMENT_FILE']
except KeyError:
env_file = os.path.expanduser('~/.irods/irods_environment.json')
with iRODSSession (irods_env_file = env_file, application_name = "myApp") as session:
session.collections.get('/{0.zone}/home/{0.username}'.format(ses …
```
=> [211] set and report application name to server 

irods/connection.py, irods/pool.py, irods/session.py, irods/test/pool_test.py
In a previous PR (https://github.com/irods/python-irodsclient/pull/218), I added logic to re-create a connection is if it was not used more than a configurable amount of time. This was to deal with dropped irods connections in our Galaxy server after some period of inactivity.
After deploying this change, noticed that connections that were used recently, but were created along time ago, were still being dropped. Hence, changed the logic so any connection that was created more than a  configurable amount of time ago are re-created. This change stopped the dropped connection issue we were seeing.
=> Use connection create time (not last used time) to decide whether a connection needs to be re-created

irods/exception.py, irods/manager/user_manager.py, irods/manager/zone_manager.py, irods/models.py, irods/session.py, irods/test/zone_test.py, irods/zone.py
Allows creation of zone entries, and foreign-zone user entries, in ICAT via the client.
=> 227 228 zone user

README.rst, irods/api_number.py, irods/manager/metadata_manager.py, irods/message/__init__.py, irods/meta.py, irods/test/helpers.py, irods/test/meta_test.py
To address #244 .
This is a WIP and should be adjusted to accommodate a more succinct syntax.
We start by just jamming in the JSON directly ...
```python
ses=get_session()
reqs = {
"entity_name": "/tempZone/home/rods/thing.cc",
"entity_type": "data_object",
"operations": [
{
"operation": "remove",
"attribute": "a1",
"value": "v1"
},
{
"operation": "add",
"attribute": "a2",
"value": "v2",
"units": "u2"
}
]
}
ses.metadata.atomic( reqs )
```
It possibly should look more like ...
```
sys.metadata.atomic ( [ 'remove', iRODSMeta( 'a1','v1') ] ,   [ 'add', iRODSMeta( 'u2','v2',u2') ] , #...
)
```
or even:
```
[data|resc|coll|user].metadata.atomic ( [...],[...],...)
```
=> atomic metadata call for PRC

irods/connection.py, irods/manager/user_manager.py, irods/message/__init__.py, irods/password_obfuscation.py, irods/test/temp_password_test.py, irods/user.py
Our users login to our iRODS web application using federated SAML. The web application talk to iRODS as that user, by using the iRODS proxy user and a rodsAdmin account. To offer webdav access to our users, we're using the temporary password functionality to create a short-lived password. 
So far we were using the PHP API for this. But we're migrating to Django. So we needed the temp password functionality also in the Python.
This adds temp password functionality to the Python API. Both the function for setting your own temp password, or setting someone else temp password (as rodsAdmin). For the temp_password_for_user() I've also added a test.
=> Add functions to retrieve temp password for own user or other user (as rodsAdmin)

README.rst, irods/session.py
In issue #269  fix, in session cleanup ( ),  store account object returned from configure ( ) into a session object attribute. This was an omission in  776e9dcbc1a2b3df87dbd38e92624327bf3bf31b
=> More cleanup

irods/exception.py, irods/test/data_obj_test.py
Validates (from the Python client perspective) the commits:
- https://github.com/irods/irods/commit/6d89ca1
- https://github.com/irods/irods/commit/d8a7471
- https://github.com/irods/irods/commit/42d54aa
- https://github.com/irods/irods/commit/1b80f3a
which now allow:
- marking an out-of-date replica as stale (refer to last line of
https://github.com/irods/irods/issues/5548#issuecomment-919506139)
when another replica is written by the client
- writing in parallel mode to data objects on replication resources as
well as to non-unique replicas on the system (ref: irods/irods#5848)
=> [285] adds tests for irods/irods#5548 and irods/irods#5848

irods/collection.py, irods/manager/access_manager.py, irods/test/access_test.py, irods/test/collection_test.py
Mainly to show an example of this, and mimic the behavior of ichmod
ie. setting user and zone to "" when (no)inherit is the access_name.
Also, uses the new inheritance attribute of collections.
=> test setting/resetting inheritance

irods/message/__init__.py, irods/message/quasixml.py
I've taken a stab at solving protocol incompatibility issues on the client side.
Backticks apparently were not the only issue: If I understand correctly, most control characters 0-31, are not even encodable in XML without resorting to e.g. base64 encoding the whole element body. Yet control characters are valid both as UTF-8 and as iRODS object names, resulting in the linked issue. 
Currently, the iRODS protocol is not 100% compatible with XML, and as such, XML libraries cannot be reliably used for parsing it.
This PR implements a small parser to replace xml.etree.ElementTree, that should cover the entire iRODS XML protocol. We've run a few successful tests with some of our own Python programs. @alanking 's example code from irods/irods#4132 also produces correct output with this patch …
=> Fix irods/python-irodsclient#170: Parse current iRODS XML protocol

irods/message/__init__.py, irods/message/quasixml.py, irods/test/data_obj_test.py, irods/test/message_test.py
Allow special characters in object names, including XML-special entities like` & < > " ' `etc
=> iRODS Xml-protocol compatibility

irods/connection.py, irods/message/__init__.py
If context string being passed in via authPlugin* API is too long
(>=MAX_NAME_LEN) we must use the more flexible, less generic pamAuth...
Cleared up logic and rebased to current `main` branch
=> [279] allow long tokens via PamAuthRequest packing instr.

irods/test/data_obj_test.py
With this commit, all tests are passing under CI / docker compose.
The test routine test_object_names_with_nonprintable_chars( )
had been failing when running under the Jenkins client dot,
due to an attempt to register it from a local directory not shared
by the server node.
=> [170][3] registered file must be in shared dir

README.rst, irods/message/__init__.py, irods/results.py, irods/test/data_obj_test.py, irods/test/meta_test.py, irods/test/query_test.py, irods/test/unicode_test.py, setup.py
Add the SECURE_XML option to PRC, and make the `ET( )` call more flexible as far as changing and reverting XML parser behavior.  Slightly alter the the environment variable(s) that dictate XML parser global defaults to make better sense.
=> Defused xml

README.rst, irods/rule.py, irods/test/rule_test.py
Demo:
```
#!/usr/bin/env python3
import irods
from irods.rule import Rule
from irods.test.helpers import make_session
import io
session = make_session()
RuleFile = io.StringIO( """hw {
helloWorld(*message);
writeLine("stdout", "Message is: *message ...");
writeLine("stdout", "Message2 is: *msg2 ...");
}
INPUT   *msg2='good-bye'
OUTPUT  ruleExecOut
""")
r = Rule(session, rule_file = RuleFile,
#params={'*msg2':"'goodbye'"},
#output = 'ruleExecOut'
)
output = r.execute()
if output and len(output.MsParam_PI):
buf = output.MsParam_PI[0].inOutStruct.stdoutBuf.buf
if buf: print(buf.rstrip(b'\0').decode('utf8'))
```
The above works also if the INPUT and OUTPUT lines are omitted and the params and output keywords are instead used to convey the necessary values the Rule constructor
=> [336] rule files can now be submitted from a memory file object

README.rst, irods/exception.py, irods/manager/data_object_manager.py, irods/parallel.py
More-or-less the PRC end of the capability behind the UGM S3 parallel put/get Lightning Talk.
Send numthreads/datasize kw on first open( ) operation in the S3 plugin.
Conform with iput/iget per-thread byte counts
Data objects' open(...) in PRC can now be deferred operations, to simplify the code organization for the auto-switching parallel put.
=> changes for parallel put to S3

irods/connection.py, irods/session.py, irods/test/login_auth_test.py, irods/user.py
An uninitiated session (represented by an iRODSSession object
with pool attribute of None) was, upon deletion, calling cleanup()
despite having no connections (idle or active) to clean up. This
corrects the bug and prevents the error message that was spooling
to the console as a result.
=> [315] skip cleanup() if session.pool is None

irods/message/__init__.py, irods/test/connection_test.py, irods/test/pool_test.py
- don't use f"" style strings
- getblocking socket method doesn't exist before Python3.7
- skip test that makes logging explode in client dot
- in test, do not assert a connection fails disconnect() the second time.
=> [_3][_345] Allow tests to pass and accommodate older Python

irods/manager/metadata_manager.py, irods/message/__init__.py, irods/test/meta_test.py, irods/test/ticket_test.py, irods/ticket.py
I had incorrectly assumed the ability to add the `KeyValPair_PI` to the end of the packStruct message would be dependent on server version.  With this change we'll be sending with the keyvalpair part (necessary for the admin flag in the metadata API) regardless of server version.  It will then be ignored by the older servers, which don't need that options part anyway.
=> [#369] Simplify code for metadata and ticket APIs

README.rst
The example for accessing the error codes misses which module to load, this PR adds that.
=> Error Stack example omits module loading instruction

irods/manager/user_manager.py, irods/test/admin_test.py
Switch from making groupadmin requests via GeneralAdminRequest to UserAdminRequest.
=> [374] Use alternate endpoint for groupadmin requests

irods/resource.py, irods/test/resource_test.py
Main motivation is avoid ambiguity: new properties `resc.parent_id` and `resc.parent_name` are explicit in what they provide, whereas `resc.parent` (an already existing iRODSResource attribute) is just what Genquery returns in RESC_PARENT (that is, the parent's name on iRODS <= 4.1 and parent's ID on iRODS >=4.2) See #392
=>  [#392] expose parent_id, parent_name and resc_hierarchy for resource objects

irods/access.py
Creates two dictionaries, allowing bidirectional access between access codes (integers) to corresponding strings and vice versa.  Where integers are keys, an orderedDict is used.  
So we can do this to get a neat and succinct table of codes:
```
>>> import irods.access, pprint
>>> pprint.pprint(tuple(irods.access.iRODSAccess.strings.items()))
((1000, 'null'),
(1010, 'execute'),
(1020, 'read_annotation'),
(1030, 'read_system_metadata'),
(1040, 'read_metadata'),
(1050, 'read_object'),
(1060, 'write_annotation'),
(1070, 'create_metadata'),
(1080, 'modify_metadata'),
(1090, 'delete_metadata'),
(1100, 'administer_object'),
(1110, 'create_object'),
(1120, 'modify_object'),
(1130, 'delete_object'),
(1140, 'create_token'),
(1150, 'delete_token'),
(1160, 'curate'),
(1200, 'own'))
```
=> [#420] store integer codes & strings for access levels

irods/manager/access_manager.py, irods/test/access_test.py
`session.acls`  (which supercedes `session.permissions` and defaults the report_raw_acls parameter to `True`) now removes non-existent user IDs from its internal calculations (because iRODS currently does not - refer to https://github.com/irods/irods/issues/6921)
=> [#431][irods/irods#6921] allow session.acls to function despite removed users

irods/message/__init__.py, irods/test/meta_test.py
**Edit:** superceded by events.  
**This previously read:**
We can now do obj.metadata.set('attr',i) where i is an integer, and not worry about message truncation when i == 0.
**But, right here and now:**
It seems we've decided that fields passed over the wire must be strings or None. (None is allowed only in the **units** field, and even then it's represented as a zero-length string on the wire.)  AVUs (as represented by `irods.meta.iRODSMeta` ) must by convention have attribute and value fields that are non-zero-length strings (even though `imeta set -d <path> attr ""` setting an AVU with an empty value field is still permitted in iCommands as of iRODS 4.2.11.)
PRC will enforce this convention / restriction by raising an error when attempting to send non-string (or zero-length) …
=> [#434] AVU fields must be strings (and all but units must be non-null)

irods/column.py, irods/test/query_test.py
A new class, irods.column.NotLike, the logical negation of irods.column.Like, is introduced. It implements "NOT LIKE" in the GenQuery syntax.
=> add the general query NOT LIKE operator

irods/message/__init__.py, irods/meta.py, irods/test/meta_test.py, irods/test/query_test.py
Here we patch the ModAVUMetadata interface in the Python client to allow both Unicode and bytestring fields everywhere, regardless of which string type is the norm for the running Python interpreter.
Included also:
- a test to ensure metadata queries, also, can match bytestring and Unicode equally well
- an extra test that creates one data object with a unicode name, but queries for it using the bytestring equivalent.
=> Allow non-default string types in all metadata calls

irods/manager/user_manager.py, irods/test/user_group_test.py, irods/user.py
The `modify_password` call uses USER_ADMIN_AN (aka rcUserAdmin)'s sub-interface "userpw" and is available for rodsusers to change their own passwords.  Various exceptions can bubble up in this call, including CAT_PASSWORD_ENCODING_ERROR and PASSWORD_EXCEEDS_MAX_SIZE.  Here we regularize this by pre-screening parameters that might cause such a server error and throwing up a single Exception type (`Bad_password_change_parameter`) instead.
This also prevents a user from being able to corrupt the catalog entry containing their password which is possible in all server versions to date up to 4.3.0 and 4.2.11, probably including 4.2.12 as well. Notably the userpw interface throws no error when this corruption happens.  An attempt to change the password to something 25 chars or longer when an …
=> protect against use of bad parameters in modify_password

irods/__init__.py, irods/manager/user_manager.py, irods/message/__init__.py, irods/models.py, irods/test/user_group_test.py, irods/user.py, irods/version.py
With this change, we can now use the `irods.models.Quota` class to discover group user guotas...
A client endpoint has also been added for creating and removing group quotas. (individual user quotas aka `iadmin suq` are no longer supported.)
=> [#474] include query model to discover quotas

README.rst, irods/client_configuration/__init__.py, irods/message/__init__.py
This PR supplies the infrastructure to load a choice for (default) XML parser to be used in a PRC interpreter instance.
Some tricks of the Python trade are necessary, like allowing settable properties to alias to an already established variable state that determines a pre-existing PRC behavior. (Such was the case for the XML parser.)
=> [#485] Writeable properties metaclass and loadable xml parser setting

irods/__init__.py, irods/account.py, irods/auth/__init__.py, irods/auth/native.py, irods/auth/pam_password.py, irods/client_configuration/__init__.py, irods/connection.py, irods/session.py, irods/test/pam.bats/funcs, irods/test/pam.bats/test001_pam_password_expiration.bats
Provides a client compatibility layer for the iRODS 4.3 authentication framework.
Presently we still rely on the the old routines (for example, we call back to `irods.Connection._login_pam` when attempting the "pam_password" auth scheme).  But this dispatch-to-module approach is likely to be more maintainable/extensible than the legacy way of doing things.
=> client "plugin" modules for authentication.

README.rst
This pull request only documents pam related settings.  It really consists of only one commit, "document new legacy_auth.pam.* settings ", but is rebased to its proper position relative to PR 486 on which it depends.
To elaborate: 
Pull Requests
- #486, 
- #461 (having #486 as a prerequisite), and
- this one (documenting #461)
should be merged in that exact order.
=> Document pam settings

irods/manager/access_manager.py, irods/session.py, irods/test/access_test.py
The idea is to remove all traces of `<session>.permissions`, deprecated since v1.1.7
=> [_510] change permissions to acls

README.md, irods/auth/pam.py
Basically we're changing the README here to add background about "pam" vs. "pam_password" scheme strings, and altering the error message to be more user-friendly and cogent when attempting to use an "irods_authentication_scheme" setting of "pam" under iRODS 4.3+
=> [521] clearer documentation and errors regarding pam/pam_password

README.md, irods/pool.py, irods/session.py, irods/test/connection_test.py, irods/test/helpers.py
Needs a test or two.
(Tests should include evaluating whether the new code works for SSL sockets.)
=> [#569] fix stored connections to match desired connection timeout

irods/access.py, irods/test/access_test.py
Addresses #558 (I think?)
The new tests failed as expected before fix and then passed as expected after fix. Also confirmed that `irods.test.access_test.TestAccess` passes.
I didn't bother testing / handling other types because I'm not sure how deep we want to go here. Happy to discuss this.
=> [#558] iRODSAccess: Handle iRODSCollection and iRODSDataObject

README.md, irods/manager/data_object_manager.py, irods/parallel.py, irods/test/data_obj_test.py
Designed in such as way as to be foreseeably generic and /or adaptable to multiple progress bar libraries.  `progressbar` and `tqdm` are  demonstrated as compatible.
This PR may end up supplanting https://github.com/irods/python-irodsclient/pull/575
=> Add progress bar update capability to data transfers in iRODS

irods/test/setupssl.py
`--help` option added to `setupssl.py` script, as `-h` was already taken.
See https://github.com/irods/python-irodsclient/issues/537#issuecomment-2263239631
=> [#537] add --help option

irods/api_number.py, irods/exception.py, irods/session.py, irods/test/library_features_test.py
=> [#556] implement library features

irods/client_configuration/__init__.py, irods/test/data_obj_test.py, irods/test/modules/test_xml_parser.py
See [issue description](https://github.com/irods/python-irodsclient/issues/584).  Basically this change means that you won't have to declare a config file path in the environment  (even if that value is null length, denoting the default path of `~/.python_irodsclient`) in order to get the environmental overrides to work.
=> [#584] load settings from environment without a config file present

irods/test/access_test.py, irods/test/genquery2_test.py
The test:
`irods.test.access_test.TestAccess.test_iRODSAccess_cannot_be_constructed_using_unsupported_type__issue_558
`
=> [#3] test calling assertRaisesRegex fails on Python2

irods/test/resource_test.py
I’m considering packaging this in Fedora Linux. I don’t have the ability to test this with a real iRODS grid, so I’m using an import-only “smoke test” as a sanity check. I found that `irods.test.resource_test` fails to import, at least on Python 3.13, with an `ImportError` like the following:
```
File "/builddir/build/BUILD/python-python-irodsclient-2.1.0-build/BUILDROOT/usr/lib/python3.13/site-packages/irods/test/resource_test.py", line 14, in TestResource
from helpers import create_simple_resc_hierarchy, create_simple_resc
ModuleNotFoundError: No module named 'helpers'
```
Maybe this works on older Python interpreters – I’m not sure – but this PR fixes the problem in a way that should be compatible with *all* Pythons.
=> Fix an import in the tests that doesn’t seem to work as intended

irods/message/__init__.py
Update the client library's advertised server compatibility to 4.3.3 in preparation for that release.
That this did not happen for release v2.1.0 will not be not an upgrade blocker for most.  It affects only the generation of `iRODSSession` objects by the use of `irods.test.helpers.make_session`, because this call would fail when run with the default parameter value of ` test_server_version = True` and connecting to an iRODS 4.3.3 server.  To any users for whom this presents a problem, please import and use `irods.helpers.make_session` instead.
=> [#3] tweak compatibility to iRODS 4.3.3

README.md, irods/connection.py, irods/message/__init__.py, irods/test/meta_test.py
Includes test with `atomic_metadata`.
Other APIs that could use this feature include `replica_truncate` and `atomic_apply_acls`
=> [#606] attach server response message to exception

irods/__init__.py, irods/session.py, irods/test/connection_test.py
Prevent PRC from blowing up when excessive socket timeout values are used.
This is  more of a Python or libc underlying problem from the  but we want to be proactive and cap the value to its maximum practicable value for the benefit of projects relying on PRC.
=> [#623] hard-limit large connection timeouts

README.md, irods/__init__.py, irods/account.py, irods/client_init.py, irods/connection.py, irods/session.py, irods/test/PRC_issue_362.bats, irods/test/helpers.py, irods/test/pam.bats/test001_pam_password_expiration.bats, irods/test/scripts/test002_write_native_credentials_to_secrets_file.bats, irods/test/scripts/test003_write_pam_credentials_to_secrets_file.bats, irods/test/scripts/test004_prc_pam_password_internal_secrets_file_generation.bats
Capability for PRC to generate a PAM-based .irodsA authentication file, as iinit does when pam_password is the authentication scheme.
=> [#517] allow generating a pam-password based .irodsA if not pre-existing

irods/test/meta_test.py
Check that `irods.helpers.xml_mode` (#586) addresses #582
=> Create a test to demonstrate xml_mode allows setting nonprintable AVUs

irods/session.py
Other parts of the error dump (detailng three levels of stacked exceptions) already give enough complexity for the troubleshooter to deal with, so this change helps us by avoiding a fourth: a SyntaxError easily avoided by jumping around the situation we found ourselves in with #641, and that was doing an eval on a string that could be empty.  Bad progammer!
=> [#641] avoid unnecessary SyntaxError message

README.md, irods/client_init.py, irods/test/scripts/test002_write_native_credentials_to_secrets_file.bats, irods/test/scripts/test003_write_pam_credentials_to_secrets_file.bats
A new parameter named "overwrite", determines whether an old file will be overwritten, and defaults to True.
Also: we add a helper function `_open_for_protected_content`, a context manager which encapsulates the opening for write, writing, and closing of a file with protected content (ie only readable by the owner, using a umask of 077 octal by default).
=> [#635]  client_init free functions can now suppress overwriting old .irodsA

irods/client_init.py
I think this rounds out what we need as documentation in the script. b4599282a362ebf4ca069342ff26fb097585bef4 has now  also provided docstrings for the public-facing free functions of this module
=> [_654] further documentation of script in usage help

irods/column.py, irods/test/collection_test.py, irods/test/data_obj_test.py, irods/test/meta_test.py, irods/test/query_test.py
not tested, just find/replaced.
@d-w-moore please run this through testing
=> [670] replace use of deprecated utcfromtimestamp

irods/version.py
builds correctly, passes `twine check`.
this will be a Py3-only PyPI release.
=> [664] bump version to v3.0.0

setup.cfg
Fixes:
```
/usr/lib/python3.13/site-packages/setuptools/dist.py:452: SetuptoolsDeprecationWarning: Invalid dash-separated options
!!
********************************************************************************
Usage of dash-separated 'description-file' will not be supported in future
versions. Please use the underscore name 'description_file' instead.
This deprecation is overdue, please update your project and remove deprecated
calls to avoid build errors in the future.
See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
********************************************************************************
!!
opt = self.warn_dash_deprecation(opt, section)
```
=> Replace deprecated description-file with description_file

irods/test/admin_test.py, irods/test/data_obj_test.py, irods/test/rule_test.py
Change strings with backslashes that are not intended to be part of backslash escape sequences to raw strings. Most but not all such strings are regular expression patterns.
Fixes a number of instances of:
```
SyntaxWarning: invalid escape sequence
```
----
Before this PR:
```
$ find . -name '*.py[co]' -delete
$ python3.13 -m compileall irods | grep Syntax
irods/test/admin_test.py:379: SyntaxWarning: invalid escape sequence '\]'
new_password = """abc123!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~Z"""
irods/test/admin_test.py:406: SyntaxWarning: invalid escape sequence '\]'
new_comment = """comment-abc123!"#$%&'()*+,-./:;<=>?@[\]^_{|}~Z"""  # omitting backtick due to #170
irods/test/admin_test.py:425: SyntaxWarning: invalid escape sequence '\]'
new_info = …
```
=> Fix some SyntaxWarnings in the tests

irods/test/collection_test.py, irods/test/data_obj_test.py
Delete objects before GC if their proper destruction depends on doing so before interpreter finalization (ie. the garbage collection phase)
=> [#711] restore balancing del statement.

irods/helpers/__init__.py
When `StopTestsException` was moved to `irods.helpers` from `irods.test.helpers`, the import os should have been added at the head of `irods/helpers/__init__.py`
This corrects the omission.
=> [#750] import os module for StopTestsException

README.md, irods/column.py, irods/query.py, irods/test/query_test.py
New usage: Applying the negation of a column, as a parameter to <session>.query(...), will remove the column from the result.
=> [#755] negation of columns

.github/workflows/main.yml, irods/exception.py, irods/manager/data_object_manager.py, irods/manager/metadata_manager.py, irods/message/__init__.py, irods/message/ordered.py, irods/message/quasixml.py, irods/models.py, irods/parallel.py, irods/prc_write_irodsA.py, irods/test/data_obj_test.py, irods/test/helpers.py, irods/test/login_auth_test_must_run_manually.py, irods/test/message_test.py, irods/test/meta_test.py, irods/test/pool_test.py, setup.py
=> [744] Add mypy type checking
